# Generated by Django 4.2.7 on 2023-11-20 03:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_shoppingaddress_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=uuid.uuid4, max_length=200, unique=True),
        ),
    ]
