# Generated by Django 4.2.7 on 2023-11-24 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
    ]
