# Generated by Django 4.2.7 on 2023-11-25 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_size_productsize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
